name: Calculate weekly emissions

# Run at 06:00 on every Sunday
on:
  schedule:
    - cron: '0 6 * * */7'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Calculate emissions
      run: |
        python calculate_emissions.py > emissions.txt
    - name: Upload result
      uses: actions/upload-artifact@v2
      with:
        name: emissions
        path: emissions.txt
